# Generated by Django 3.1 on 2020-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('college', models.CharField(max_length=124, null=True)),
                ('group', models.CharField(choices=[('Sience', 'Sience'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=32, null=True)),
                ('passing_year', models.IntegerField(null=True)),
                ('GPA', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('schoole', models.CharField(max_length=124, null=True)),
                ('group', models.CharField(max_length=32, null=True)),
                ('passing_year', models.IntegerField(null=True)),
                ('GPA', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('varsity', models.CharField(max_length=124, null=True)),
                ('degree', models.CharField(choices=[('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('PhD', 'PhD'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('Diploma', 'Diploma')], max_length=32, null=True)),
                ('feild', models.CharField(max_length=32, null=True)),
                ('passing_year', models.IntegerField(null=True)),
                ('CGPA', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinformation',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
