# Generated by Django 3.1 on 2020-08-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200817_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruniversity',
            name='degree',
            field=models.CharField(choices=[('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('B.A', 'B.A'), ('M.Sc', 'M.Sc'), ('M.A', 'M.A'), ('M.Com', 'M.Com'), ('PhD', 'PhD'), ('Diploma', 'Diploma')], max_length=32, null=True),
        ),
    ]
