# Generated by Django 3.1 on 2020-08-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200817_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInformation',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userschool',
            old_name='schoole',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='usercollege',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userschool',
            name='username',
        ),
        migrations.RemoveField(
            model_name='useruniversity',
            name='username',
        ),
        migrations.AddField(
            model_name='usercollege',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo'),
        ),
        migrations.AddField(
            model_name='userschool',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo'),
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo'),
        ),
    ]
