# Generated by Django 3.1 on 2020-08-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userschool_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='First_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectTitle', models.CharField(max_length=32, null=True)),
                ('usededenv', models.CharField(max_length=124, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserPassion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserExperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkTitle', models.CharField(max_length=32, null=True)),
                ('CompanyName', models.CharField(max_length=124, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=32, null=True)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('religion', models.CharField(max_length=32, null=True)),
                ('blood_group', models.CharField(max_length=32, null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, null=True)),
                ('First_name', models.CharField(max_length=32, null=True)),
                ('Last_name', models.CharField(max_length=32, null=True)),
                ('Nationality', models.CharField(max_length=32, null=True)),
                ('CurrentAddress', models.CharField(max_length=124, null=True)),
                ('PermanentAddress', models.CharField(max_length=124, null=True)),
                ('ZipCode', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=32, null=True)),
                ('field', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=124, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinfo')),
            ],
        ),
    ]
