# Generated by Django 3.1 on 2020-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200817_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password1',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password2',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
