# Generated by Django 3.1 on 2020-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200817_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='First_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='email',
            new_name='First_name',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password2',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Last_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
