# Generated by Django 3.1 on 2020-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200817_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='aboutme',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
